name: Daily Macro Notifier

on:
schedule:
\# 平日08:00 JSTに自動実行 (UTC 23:00)
\- cron: '0 23 \* \* 1-5'
workflow\_dispatch:

jobs:
notify:
runs-on: ubuntu-latest
env:
SLACK\_WEBHOOK: \${{ secrets.SLACK\_WEBHOOK }}
TE\_API\_KEY: \${{ secrets.TE\_API\_KEY }}
HF\_TOKEN: \${{ secrets.HF\_TOKEN }}
steps:
\- name: Checkout repository
uses: actions/checkout\@v3

```
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'

  - name: Install dependencies
    run: |
      pip install --upgrade pip
      pip install -r requirements.txt

  - name: Run notifier
    run: python main.py
```

