name: Daily Macro Notifier

on:
schedule:
\# 平日08:00 JSTに自動実行 (UTC 23:00)
\- cron: '0 23 \* \* 1-5'
workflow\_dispatch:

jobs:
notify:
runs-on: ubuntu-latest
env:
SLACK\_WEBHOOK: \${{ secrets.SLACK\_WEBHOOK }}
TRADING\_ECONOMICS\_API\_KEY: \${{ secrets.TRADING\_ECONOMICS\_API\_KEY }}
steps:
\- name: Checkout repository
uses: actions/checkout\@v3

```
  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.x'

  - name: Install dependencies
    run: pip install -r requirements.txt

  - name: Run notifier
    run: python main.py
```
