import os
import json
import requests

# 通知用Webhookの取得
webhook = os.environ.get("SLACK_WEBHOOK")

# 送信するSlackメッセージ（テスト）
payload = {
    "text": ":bug: Slack通知テスト - デバッグ用"
}

# --- デバッグ出力 ---
print("\n========== Slack通知デバッグ ==========")
print("[Webhook URL]", webhook)
print("[送信内容]", json.dumps(payload, ensure_ascii=False))
print("======================================\n")

# SlackへPOSTリクエスト
try:
    if not webhook:
        raise RuntimeError("SLACK_WEBHOOKが取得できていません。環境変数を確認してください。")

    response = requests.post(webhook, json=payload)
    print(">>> Slack HTTP status:", response.status_code)
    print(">>> Slack response body:", response.text)

    if response.status_code != 200:
        raise RuntimeError(f"Slack通知失敗: {response.status_code} - {response.text}")
except Exception as e:
    print(">>> Slack POST Error:", e)
