name: Daily Macro Notifier

on:
  schedule:
    # 平日 08:00 JST に自動実行 (UTC 23:00)
    - cron: '0 23 * * 1-5'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      TRADING_ECONOMICS_API_KEY: ${{ secrets.TRADING_ECONOMICS_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # 以下、必要なステップを記述…

