name: Daily Macro Notifier

on:
  schedule:
    - cron: '0 23 * * *'   # JST 08:00
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install -r requirements.txt

      - env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: python main.py
