name: Daily Macro Notifier

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'   # 08:00 JST 毎日

jobs:
  notify:
    runs-on: ubuntu-latest
    # --- Secrets を環境変数として渡す -------------------------
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      TRADING_ECONOMICS_API_KEY: ${{ secrets.TRADING_ECONOMICS_API_KEY }}
    # ----------------------------------------------------------

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run notifier
        run: python main.py
